### ISSUE TITLE
createRGB: Error: JAI cannot be resolved

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#1]
@pcampanella please check it [here at line 69](https://github.com/fadeoutsoftware/WASDI/blob/a1c1d69ad0f6e5c37733206cae38d9754bff043b/wrappersnap/launcher/src/main/java/Proofs_BandImage.java#L69). Maybe JAI definition was accidentally deleted?

**Comment by pcampanella** [comment]
Yes you are right. Need to remove that comment.
But it should be definied if you uncomment, isn't it?
