### ISSUE TITLE
products footprints stay on map

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#106]
Search: set your query, search, see the results and their footprints. Now go back to the search: the footprints remain visibile on the map

# Related:

- [Search Redesign](https://github.com/fadeoutsoftware/WASDI/issues/47) #47

**Comment by pcampanella** [comment]
Let's have a discussion about this. From one side I agree, from the other can be useful to change filters but in the same area. I'm confused about the best option.

**Comment by kr1zz** [comment]
Sure. I think I see your point. For the moment, these are two potential alternatives that come to mind:

1. the rectangle drawn by the user is kept (unless explicitly removed, which is a functionality we might consider improving ;) ), whereas the footprints of the products from the previous search are removed
1. same as before but the user can toggle the footprints by means of a switch

**Comment by kr1zz** [comment]
See also #124
