### ISSUE TITLE
Show footprint of selected product (Editor)

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#108]
Open the editor: remembering what a product is from its name can be challenging for most of us. I'd find it useful if the *Geographic View* and the cesium panel both performed an automatic zoom onto the area to show the footprint (or a preview, if possible) of the product.

**Comment by pcampanella** [comment]
You mean in the Navigator Pain or in general geographic mode?

**Comment by kr1zz** [comment]
I'd say In the navigation pane and, if selected, in the Geographic view. I mean the same behavior that happens when a published band is selected.

**Comment by pcampanella** [comment]
This should be possibile with the right click on a band. The user can zoom on 2d or 3d map.
In this moment, the 2d zoom for not published bands does not work.
It works for published and for any case in 3d.
