### ISSUE TITLE
Switch from 2D geo mode to 3D mode: active layer not added to 3d map

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#110]
As per title, when the user Switch from 2D geo mode to 3D mode, active layers are not added to 3d map, while they remain checked.

**Comment by sergin13** [comment]
Ok give me an example (what products did you use? )because i'm not able to reproduce this problem...

**Comment by pcampanella** [comment]
For example with my account - official Line
Go in the eDRIFT Workspace
Go in geographic mode
Open the S1B_IW_GRDH_1SDV_20170830T122203_20170830T122232_007169_00CA2C_E7BF_flood_map.tif
Band 1 Layer
Switch to 3d Mode
The layer is not added to the map while it should.
