### ISSUE TITLE
Import (Search): the system ask the total count at every page switch

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#113]
Every time the user make a search the system ask for the count and then the first page. When the user change the page (ie next) the system looks to query again for the total count but this should be avoided.

**Comment by kr1zz** [comment]
A note, maybe we should add another issue, but it might be somehow (indirectly?) related. I haven't found a way to reproduce this systematically yet. If one starts paging with 10 entries per page, then after navigating some pages, switches to more entries per page, say 50, then sometimes an error occurs when navigation is continued.

**Comment by sergin13** [comment]
> Every time the user make a search the system ask for the count and then the first page. When the user change the page (ie next) the system looks to query again for the total count but this should be avoided.

It's necessary because (for example) copernicus with the same query request it could be have a different number of results (if i look for the products of today during the day the number of ingested product increase)
