### ISSUE TITLE
Ingest file: the system does not control if a file with the same name already exists and creates a new product with the same name

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#114]
In the Ingest file Launcher operation the system does not control if a file with the same name already exists and creates a new product with the same name.

The problem appears for sure when a mosaic is done. We have to check the output of other operations and of the workflow.

The big problem is that 2 files in two different workspace with the same name can conflict in this way!!!

**Comment by kr1zz** [comment]
Before assigning a name to the newly created product we could check if that name already exists. If it does, we could hash both files (or set of files) to see if they are the same. If they are the same we don't need to save the file. If they are different we could modify the file name with some unique identifier (e.g., a UUID).
(Improvement: the hash could be stored in the DB.)

Would that solve the issue?
