### ISSUE TITLE
Open Sentinel 3 Images

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#12]
Using SNAP desktop is possible to open the images after an Unzip operation.
Try if it is the same by code and if it works auto unzip S3 images after downloaded.

**Comment by kr1zz** [comment]
Just tested with (newly installed) SNAP 7: it cannot open S3 images as-is. It is however possible to open them after unzipping: I opened the manifest xml file and SNAP loaded the bands and the rest.
