### ISSUE TITLE
Add Delete Processor feature

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#129]
The system must permit users to delete their own processor.
This mean cleaning docker or file system and db.

**Comment by kr1zz** [comment]
Also, allow the user to decide whether she wishes to keep her processor private (as it can be done for workflows). And I bet there are more features in common with workflows, maybe like choosing input and outputs. Does it make sense to have a unified management interface for both processors and workflows?

**Comment by kr1zz** [comment]
Also, is there a radical difference between the items in "WASDI Apps" and those in "Processor" menus? Can we unify them too?
