### ISSUE TITLE
UI problems with small displays (or screen, or monitor) - size matters!

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#132]
With small displays there are some screens (e.g. search) which cannot be used, because part of the screen ends below the line (e.g. search: some mission-specific search filters) and the screen is not scrollable. Maybe making the screen scrollable might be a solution.
Also, the rightmost part of the bottom bar exceeds the screen width and the controls for showing the logs are not visible.

Also, the items on the right end of the process bar get wrapped on a new line on the left side.

**Comment by kr1zz** [comment]
@pcampanella @sergin13 I gave the issue P4 since probably most EO professionals work with a large screen. However, the problem is blocking on some screens, so maybe you wish to raise the priority of the issue. Please check it

**Comment by pcampanella** [comment]
@mmenapace  can you control if this is all or in part solved after your last updates?

**Comment by mmenapace** [comment]
The issue related to the processor bar are fixed.
Also, the highlighted components are now vertically scrollable, solving the issue.
To have a totally responsive UI for all screen size there's an important refactor to be done, but everything related to this issue 
is now fixed. Closing as solved.
