### ISSUE TITLE
WASDI HTTPS

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#16]
Buy and install the SSL Certificate.
Move the server and the client in HTTPS.

**Comment by odrasm** [comment]
Appena abbiamo i certificati, pingatemi.

**Comment by kr1zz** [comment]
> Appena abbiamo i certificati, pingatemi.

@taxalb

**Comment by taxalb** [comment]
Abbiamo deciso di usare Let's encrypt, non ci sono certificati da comprare

**Comment by odrasm** [comment]
avete valutato anche tempi e modalita' di aggiornamento dei certificati di let's encrypt? Se mi date un ultimo ok, procedo con quel tipo di certificati.

**Comment by taxalb** [comment]
@odrasm l'idea era di mettere in piedi il rinnovo automatico con il [protocollo ACME](https://letsencrypt.org/docs/client-options/), il client consigliato è [Certbot](https://certbot.eff.org/)

**Comment by odrasm** [comment]
ok, do' l'aggiornamento per buono e comincio con la configurazione di nginx, inizialmente direi che i due vhost puntino a cartelle diverse del client di modo da poter fare con calma le modifiche necessarie nella versione https.
Se per voi va bene posso individuare il grosso delle chiamate http e provare a passarle in https, se non ci sono servizi particolarmente, complessi ce la dovrebbo cavare.

**Comment by pcampanella** [comment]
Certo Max ottimo. Se hai bisogno chiedi!

**Comment by odrasm** [comment]
Enabled server side https with certs from https://letsencrypt.org/
