### ISSUE TITLE
Integrate ONDA DIAS Provider

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#18]
Now we have the DATA on the ONDA DIAS.

We need to implement the search provider to query the ONDA DIAS

Per quanto riguarda le API, il nostro servizio ha anche un catalogo/discovery che espone API basate su ODATA, attraverso le quali potete fare interrogazioni / search, e tra l’altro potete anche usarle per ottenere lo pseudo-path da utilizzare poi per accedere al prodotto della advanced API facendo ricerche su ODATA.
 
Per l’accesso al download dal catalogo dovreste registrarVi autonomamente dal portale www.onda-dias.eu se non gia’ fatto.
La registrazione e’ necessaria solo se dovete eseguire download dal catalogo, altrimenti tutte le query ODATA di search non richiedono account.
 
Le informazioni di accesso al catalogo sono qui: https://www.onda-dias.eu/cms/services/catalogues/?meta_service_category2=Data-Access
Per la registrazione il link e’: https://www.onda-dias.eu/crm/
Il catalogo e’ disponibile anche via browser qui: https://catalogue.onda-dias.eu/catalogue/, per il catalogo non e’ necessaria la registrazione, che serve solo per eseguire operazioni di download.
 
Dal sito e’ disponibile la voce Help che porta alle User Guide e FAQ. Se Vi registrate trovate anche ulteriore manualistica nel caso in cui non fosse sufficiente quella disponibile sul sito:
-	https://www.onda-dias.eu/cms/user-guides/
-	https://www.onda-dias.eu/cms/user-guides/catalogue-open-data-protocol-user-guide/
-	https://www.onda-dias.eu/cms/user-guides/advanced-api-user-guide/
 

Then we need to implement the Server Component that takes the data from the disk and does not download. The PROBAV one is similar.

**Comment by kr1zz** [comment]
- [ ] count
  - [ ] Sentinel-1
    - [ ]Platform:[S1A_*|S1B_*] (optional)
    - [ ]type:[SLC|GRD|OCN] (optional)
    - [ ]relativeOrbitNumber:[integer in [1-175]] (optional)
    - [ ]Sensor Mode:[SM|IW|EW|WV] (optional)
  - [ ] Sentinel-2
  - [ ] Sentinel-3
  - [ ] Landsat
  - [ ] Envisat
- [ ] execute
  - [ ] execute query
  - [ ]  parse
