### ISSUE TITLE
Issue with time filter with ONDA

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#185]
https://catalogue.onda-dias.eu/dias-catalogue/Products?$search="( ( platformName:Sentinel-2 AND platformSerialIdentifier:* AND name:* ) ) AND ( ( beginPosition:[2020-02-12T00:00:00.000Z TO 2020-02-12T23:59:59.999Z] AND endPosition:[2020-02-12T00:00:00.000Z TO 2020-02-12T23:59:59.999Z] ) ) AND footprint:"Intersects(POLYGON((17.92970579140951 51.56866516897833,17.92970579140951 51.64374756161578,18.01758214705901 51.64374756161578,18.01758214705901 51.56866516897833,17.92970579140951 51.56866516897833)))""&$expand=Metadata&$top=10&$skip=0&$format=json&$orderby=creationDate

ONDA returns 6 results, whereas the Sentinel Hub returns only 4 for the same query. Among the results returned from ONDA are these 2 which should not be present:

- S2A_MSIL2A_20200212T231651_N0214_R087_T60UXC_20200213T013708
- S2A_MSIL1C_20200212T231651_N0209_R087_T60UXC_20200213T010119

However, despite their filenames, the stop time for these two images is still on the 12th of February.

**Comment by pcampanella** [comment]
I think this is old, I close it.
Now we know not all providers have same images, this was not our bug.
