### ISSUE TITLE
Delete multiple products at once (actions on multiple products?)

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#190]
If a user needs to delete multiple products in a workspace, then she/he is forced to go through them one by one. The possibility of selecting the desired ones and delete them at once would save tedious work. Actually, other operations might be performed on the multiple selection, e.g.:
- move to another workspace
- download
- [send to FTP](https://github.com/fadeoutsoftware/WASDI/issues/283) #283 
- ...

**Comment by mmenapace** [comment]
Evaluating a refactor of the tree view. 
Discussed the possbility to add a checkbox to enable multi selection of products.
When multiple products are selected, the contextual menu applies to them.

**Comment by mmenapace** [comment]
Proposal from Paolo 
1 - Check box
2 - When a band is opened a slider can control the opacity of the image

**Comment by mmenapace** [comment]
Deployed on test

**Comment by mmenapace** [comment]
Further problem: 
the layer list is not scrollable. 
If the users add more than 4 layers some are hidden.

**Comment by mmenapace** [comment]
Also, when a new layer is added, the tab goes back to navigation
