### ISSUE TITLE
FTP file upload

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#2]
The user will define ftp credentials and the system will upload the file. Branch [feature/FTPclient](https://github.com/fadeoutsoftware/WASDI/tree/feature/FTPclient)

- [x] shared: FTP client
- [x] launcher: method to upload file
  - [x] (update status)
  - [x] remove process once completed
- [x] REST API
- [x] client

**Comment by kr1zz** [comment]
@pcampanella shall we just upload the file to the root directory of the server (quicker), or shall we let the user navigate the server folders?

@sergin13

**Comment by pcampanella** [comment]
We can start with the root. 
Then I do not want the user to navigate like a full ftp client but if the user knows a path then he should be able to set it.

**Comment by kr1zz** [comment]
API Resource? (Doing it in Catalog, for now...)
