### ISSUE TITLE
Automatic Login with google - Disable?

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#20]
It looks that if a user logs in once, in any PC, then if the same user is google-logged also on another PC the system logs in him automatically in WASDI.

We need to investigate the behaviour because it is not clear and maybe not safe.

Try to reproduce and understand as a first step. Need to have two PC, the first to create the wasdi google account, in the second log in google and then try to log in WASDI.

**Comment by mmenapace** [comment]
The google login is now handled by Keycloak, and the problematic 
behaviour no longer exists
