### ISSUE TITLE
Plan - time limit in the future?

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#22]
It looks that if you try to plan in more then 1 or 2 months in the future does not find any result.
Can we reproduce it?
Is there any limit? 
This issue is just to try. There should be no limit on the server. Make a test on the client.

**Comment by sergin13** [comment]
I don't think is a bug, the providers have different times limit in the future (COSMO-SKYMED have the farthest time horizon), apparently there aren't errors ...
