### ISSUE TITLE
Workspace deletion does not stop running processes (kill running processes before)

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#230]
What if we delete a workspace where processes are still running? I bet the files and directory get deleted without check. What if a running processor then tries to create a file? Does it create the directory? Is that directory referenced anywhere in the DB? That's a recipe for a mess.

One possibility is to ask the user if the running processes (if any) shall be terminated. If so, kill them, wait for the kill to complete, then proceed as usual. Else? Just wait for the processes to complete?

**Comment by kr1zz** [comment]
Do not delete a workspace if there are processes running

**Comment by mmenapace** [comment]
Forbid running processes in WS that are about to be deleted

**Comment by kr1zz** [comment]
Check this one too:
[Delete workspace with running applications: launcher process can hang on the server](https://github.com/fadeoutsoftware/WASDI/issues/349) #349
