### ISSUE TITLE
Time counter keeps going

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#231]
The timer keeps running even after the process terminated or has been killed.

Possibly related:

- [Client timer repeatedly resets before download is completed](https://github.com/fadeoutsoftware/WASDI/issues/145) #145

**Comment by pcampanella** [comment]
I think this is no more reproducible: just test and eventually close.

**Comment by bspurgeon08** [comment]
Tested and behaviour is slightly different in Firefox vs Chrome:
Firefox - Original process starts over at 0 and begins counting until the killprocesstree action is complete
Chrome - Original process keeps going
