### ISSUE TITLE
Workflow Window: User Experience and Restyle.

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#24]
The window let to upload workflows and to run. 
The user experience is not good:
 -> Add feedback after an upload success
 -> Add the SNAP logo and specify that these are SNAP Workflows
 -> In the execute, maximize the product list that now is very short: it is difficult to select the product
 -> When the user runs a workflow, close the window (not when upload only for execute)

**Comment by sergin13** [comment]
done
