### ISSUE TITLE
Editor - Right mouse menu -> Download does not work

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#25]
In the editor on right click menu the download command now starts the download but we have two problems:
1) THERE IS NO USER Feedback. I see that is downloading using Developer Tools...
2) After the download is finished, it does not save the file in the PC but tries to open the downloaded file in some way. In my PC resulted in a browser error.

To reproduce:
open WASDI.net
Open a workspace
Go in editor
Right click on a product and select download.

**Comment by sergin13** [comment]
I'have tried to resolve this problem, unfortunately i can't test on my local copy @pcampanella

**Comment by pcampanella** [comment]
For me is working now. We have a problem to solve with NGINX in the server; after is solved, make some other test before close this issue.
