### ISSUE TITLE
Optimize getListByWorkspace in ProductResource

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#256]
When we open a workspace with many images it take a not reasonable time.
We should implement a lazy load.
There are already 2 similar api: getLightListByWorkspace and getNamesByWorkspace that are used for example by the lib.
The idea is to read only the names and load each product detail when neede.

**Comment by kr1zz** [comment]
Some ideas we discussed:

for the workspaces view:
1. is the list necessary? Maybe not. Or maybe we could do a lazy load
1. can we get rid of the bounding boxes? Maybe we could use just a bounding box of the workspace

for the editor view:
1. do one of these (and possibly cache the results in both case)
  1.  lazy load (paging)
  2. load just the list, and each time the user opens a node in the tree, make a call to the server to get the details of that node (metadata, bounding box)
1. use the bounding box of the workspace

Should we adopt the bounding box of the workspace, we need to automate it's update, i.e., we should update it every time a product is added, deleted or modified.

**Comment by pcampanella** [comment]
From a first search we should use the $lookup operator. 

https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/#lookup-single-equality


db.productworkpsace.aggregate([ { $lookup: { from: "downloadedfiles", localField: "productName", foreignField: "filePath", as: "downloadedFile"} } ])

The big problem is that we have a very old mongo version, 3.0.15. The support of lookup starts from 3.2
Now mongo has version 4.2

At the end, I think that before implementing the new query we need to plan a Mongodb update.

**Comment by pcampanella** [comment]
Now the query works:

db.productworkpsace.aggregate([ {$match : { workspaceId:"c9a71ad7-90a1-4fc7-acd5-8583a4323fad"}}, { $lookup: { from: "downloadedfiles", localField: "productName", foreignField: "filePath", as: "downloadedFile"} } ])

We can make a test, but this could be not enough: from the db, it is quite slow.

Indeed maybe we can move to another update: do we need the productworkspace collection?
It was creted when downloaded files were only on one node. Then we introduced the full path for the downloaded file: this mean that they already belong to a workspace.
So probably we can delete the link table and this means that there will be no need to use lookup.

**Comment by pcampanella** [comment]
I tested and it works. This will be closed when published in production.
The problem is now only for workspaces with a very very high number of products: Bolivia has 54.000 products. The query is anyway fast but later the browser does not handle a tree so big. 
We will need to implement pagination also.
