### ISSUE TITLE
Split Download Queue for DataProvider

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#258]
Each Data Provider can have different limits on parallel donwload. For example schiub allows only 2, LSA 4, ONDA no limit etc.
At the moment the operation is unique DOWNLOAD and the relative scheduler queue has one single "upper limit". 
We need to find a way to split these queues or, better, enable the scheduler to handle different limits for different providers.
In the worst situation this can be done with new operations DOWNLOAD_ONDA, DOWNLOAD_LSA etc. 
I would prefer to avoid this situation with a kind of subtype or parameter...

**Comment by kr1zz** [comment]
Let's say we limit ONDA and LSA both to 4 separately: that would be at most 8 at a time. Would we need to limit the total too, e.g. to 6?

**Comment by pcampanella** [comment]
I don't know. Indeed, usually happens not so often. I would start without a cumulate limite and then see if it creates problems.
