### ISSUE TITLE
Workspaces View: List Of files Box => full re design

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#259]
I think that we should change that box.
I would like to see in that box: workpsace owner. People who have the access. Node where the WS is hosted. Total number of files. Total number of processes executed in that ws. Last "touch" of the workspace (if as I think it is already available info).

This means to make/update the API and to adapt the client view.

**Comment by mmenapace** [comment]
Having some problem with a single field, (the last one! ) which 
for unknown reasons, can't be referenced on the DOM.
The problem can be analyzed on feature/newWorkspaceInfoBox branch
