### ISSUE TITLE
Search Text Filter  (like)

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#26]
The text filter should work as "like" in query while it works for full string match.
I searched a file with the last 4 letters and found nothing. Added the full file name and it was found.
Modify the filter so that it search "containing text" and not "exact match".

**Comment by sergin13** [comment]
Do you talk about the search text filter in import product? Because in that case i don't think is possible ...

**Comment by pcampanella** [comment]
Yes. Why this should not be possibile? Cannot we search a product by name?!!

**Comment by kr1zz** [comment]
With ONDA it looks like:

- it is possible to search for a product using its name (not filename), e.g.: *S1A_IW_GRDH_1SDV_20190113T153246_20190113T153311_025461_02D245_CBD2* returns 1 exact result
- it is not possible to search for a product using a substring of its name, e.g.: *GRDH* returns 0 results (no difference using the initial or final part of the string)
- it is not possible to search for a product using its filename, e.g. *S1A_IW_GRDH_1SDV_20190113T153246_20190113T153311_025461_02D245_CBD2.SAFE* returns 10731460 results. Also, it looks like inserting the string "safe" causes this behavior, independently of the capitalization

Different providers may behave differently, and I may test them, but it may be more useful if we could [rethink the entire search process](https://github.com/fadeoutsoftware/WASDI/issues/32)

**Comment by pcampanella** [comment]
Considering that usually is not a used filter, it will no make major impact on the server, so we will put it in the client side.
Save the text, send the query without, filter the result on the %text%|name on client side.
What do you think?

**Comment by kr1zz** [comment]
I'd say it makes sense.
Actually, requesting and paging all the results is time-consuming, but we could do it offline once in a while (maybe every night, or in a low-traffic moment) and store the results for later search.
Also, knowing the conventions for file naming, maybe we could implement (some of) the filters not supported by ONDA (e.g., polarisation for sentinel 1 images) in a way that is transparent for the users.

**Comment by kr1zz** [comment]
I tried hacking some more at the ONDA catalogue, and these are the results I got:

- a full query -> the available results
- a (valid) filename -> 1 result
- a file extension, with or without the leading dot "." (though they keep growing as ONDA receives new images):
  - zip / .zip 10624537
  - safe / .safe 10787459
  - tar.gz / .tar.gz 2271
  - gz / .gz 0
  - tiff  / .tiff 0

**Comment by pcampanella** [comment]
I confirm the need of a client side filter, also after the last test @kr1zz made on ONDA.
I think that if we put the constrain on client side that:
    .If there is a "free text" => We need an Area Of Interest
We can use the SearchList API.
Is the same trick used for CRONTAB Searches: using a AOI results cannot be too much. Maybe in future we can add a limit in the dimension of AOI.

I would like to start implementing this filter, then I agree to understand some more filters from the file name, but remember it strongly depend by the mission.

**Comment by dfiori** [comment]
It looks that works with *.
Test it also on DHUS and start implemeting the auto filter on the client side.

**Comment by sergin13** [comment]
Closed (is in develop branch)

**Comment by kr1zz** [comment]
For the sake of testing:

Wrong is:

- S1A_IW_GRDH_1SDV_20190127T055034_20190127T055059_025659_02D98E_85DE : 25370
- S1A_IW_GRDH_1SDV_20190127T055034_20190127T055059_025659_02D98E_85D* : 25370
- *1A_IW_GRDH_1SDV_20190127T055034_20190127T055059_025659_02D98E_85DE : 25370
- : 25370
- * : 25370

Right should be:

- S1A_IW_GRDH_1SDV_20190127T055034_20190127T055059_025659_02D98E_85DE : 1
- S1A_IW_GRDH_1SDV_20190127T055034_20190127T055059_025659_02D98E_85D* : 1 (or few)
- *1A_IW_GRDH_1SDV_20190127T055034_20190127T055059_025659_02D98E_85DE : 1 (or few)
- : 25370 (roughly)
- * : 25370 (roughly)

**Comment by kr1zz** [comment]
example of a query which does not work as expected:

ONDA - S1 OCN:

```
http://217.182.93.57/wasdiwebserver/rest/search/query/count?sQuery=**%20AND%20(%20footprint:%22intersects(POLYGON((33.47992032766343%2035.20623093585753,33.47992032766343%2038.60208515819048,39.61273357272149%2038.60208515819048,39.61273357272149%2035.20623093585753,33.47992032766343%2035.20623093585753)))%22%20)%20AND%20(%20beginPosition:%5B2019-01-29T00:00:00.000Z%20TO%202019-02-05T23:59:59.999Z%5D%20AND%20endPosition:%5B2019-01-29T00:00:00.000Z%20TO%202019-02-05T23:59:59.999Z%5D%20)%20AND%20%20%20(platformname:Sentinel-1%20AND%20producttype:OCN)&providers=ONDA
```

But it should not have the two asterisks...

**Comment by kr1zz** [comment]
Test case: S1A_IW_GRDH_1SDV_20190131T051945_20190131T052010_025717_02DBAB_2FDC

**Comment by pcampanella** [comment]
Tested live at the phi-week and still not working.

**Comment by kr1zz** [comment]
I modified both the client and the server:

- the server appends a '*' to the free text query ONLY IF it is for ONDA, since that's the only provider for which the query is parsed
- the client appends a '*' to to the free text query

They both check that the string doesn't already end with a '*'

**Comment by kr1zz** [comment]
BTW, the file to be modified is `client/app/controllers/ImportController.js`

**Comment by kr1zz** [comment]
Note: the modification is not enough if the date interval is not coherent, e.g., if the image was acquired in 2018 and the interval is set by default in the last week (w/ year >= 2019), then the search will return 0 results.

We should either modify the search interface by disabling the time picker or informing the user with something along the line of: "No results. Are you sure the time interval is appropriate?". Alternatively, with Sentinel products, we may infer the date from the free text string, but that's going to be tricky.

**Comment by kr1zz** [comment]
Recap: is it possible to search using the product name?

- [ ] DHuS
- [ ] ONDA
- [ ] CREODIAS
- [ ] EODC
- [ ] LSA
