### ISSUE TITLE
Client Processes logs refactoring

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#278]
Finestra Processes Log:
	.aggiungere colonna Started (nota può essere null ovviamente)
	.Cambiare il bottone LOGS nella stessa icona che abbiamo nella barra di soli 5 ultimi processi
	.aggiungere un bottone tipo logs per vedere direttamente il payload sia nella dialog che nella navbar
	.Cambiare la finestra del payload che sia un semplice text box grande tipo quello che usiamo nella finestra WAPS per fare partire le app

NOTA-> ALLINEARE ANCHE LA PROCESSES-BAR.COMPONENT.HTML

**Comment by mmenapace** [comment]
Continuing the work on hotfix/NodeSelectionAndDialogFix

**Comment by mmenapace** [comment]
merged in develop after fix of icons and color style
