### ISSUE TITLE
file upload: add default style

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#291]
Allow the user to specify a default style for the file she/he is about to upload. Use a textbox, for now, and make it optional

**Comment by mmenapace** [comment]
Add a textbox under the drag and drop field in order to select a style.

Further improvements will regards the selection across the available styles, but the calls 
are distribuited so some more design considerations should be done beforehand.

**Comment by mmenapace** [comment]
on commit fb57ce76 two more get calls are created: 
- one connect always on the main node GeoServer instance to obtain the list of availabl styles 
- the second one checks the files available on the main node and retrieves a list of string corresponding to their filename(withou ".sld" extention)
