### ISSUE TITLE
Workflow: add sharings

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#297]
Add the possibility to share workflows with specific users as it is for workspaces and processors:
.Create a collection snapworkflowssharings with entites like:
{workfowId, userId, ownserId, shareDate}

.Add to the workflow window the possibility to share
.Add the API to add and delete these sharings
.Adapt the "getworkflows" API to incluce also shared workflows.

**Comment by mmenapace** [comment]
point 2: 
The sharing works. The issue was that, during the demo on DEVs meetings, I've logged in wasdi production host(wasdi.net). 
On logout event the user is redirected there from the dev machine.
