### ISSUE TITLE
Plan Section: add input filters before searching the footprints

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#3]
The plan section now allows only to choose dates and mission.
We should add more user oriented filters.
Supported by orbit are:
Looking Type
Swath Size
View Angle

These parameters must be sent to OpportunitySearchResource changing OrbitSearchViewModel.
These parameters has to be set, server side, in the InstanceFinder.findSwatsByFilters method.
In that method there is a cycle like this:
			for (SatSensor oSensor : oSatSensors) {

				boolean bEnabled = false;
				if (oSensor.getResolution().toString().toUpperCase().substring(0, 1).equals(sSensorResolution.toUpperCase().substring(0, 1) )==true) {
					bEnabled = true;
				}

				//System.out.println("SENSORE ORBIT: " + oSensor.getSName());

				// activate all sensors
				oSensor.setEnabled(bEnabled);
				// ottengo l'elenco di tutti i fasci (angoli) di
				// acquisizione disponibili per questo sensore
				ArrayList<SensorMode> oSensorModes = oSensor.getSensorModes();
				// per questo sensore attivo tutti i possibili fasci
				for (SensorMode oSensorMode : oSensorModes) {
					//System.out.println("\tMODE: " + oSensorMode.getName());
					oSensorMode.setEnabled(bEnabled);
				}
			}

The new filters must be set to the oSensor Object.

**Comment by sergin13** [comment]
done

**Comment by sergin13** [comment]
Done, there are some problems with the cosmosky and swath size fitler... In general i'm not totaly sure the results are right, the only filter i'm sure works is the look type filter
