### ISSUE TITLE
Prevent creation of multiple workspaces with the same name (at least for the same user)

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#305]
A user can create multiple workspaces with the same name. This is not managed correctly and might lead to unpredictable results. Enforce the uniqueness of workspaces names.

**Comment by ppetrescu-wasdi** [comment]
on the server side (WorkspaceResource), added a check to prevent the creation of a workspace with a name that is being already used (same name, same node, same user).
in this case, the name of the new workspace gains a "_02" termination. (i.e. TestWorkspace -> TestWorkspace_02 -> TestWorkspace_02_02 -> TestWorkspace_02_02_02).
a line of log is added to mark this occurrence.
Utils.debugLog("WorkspaceResource.CreateWorkspace: a workspace with the same name already exists. Changing the name to " + sName);
the method creates a new workspace and returns its ID.
added a test case on the same Java test class.

**Comment by pcampanella** [comment]
The solution does not work. It search always for the old name and adds _02 but then does not test again.
As a result there are many Untitled Workspace (02) instead of many Untitled Workspace.

We need to make it finer, as it is in Windows when you copy multiple files: it adds (1) (2) ... (N).

**Comment by pcampanella** [comment]
Sorry team but this does not work... It has been pushed yes?
Because I updated and published in test and still the bug is there.
Maybe just code not aligned?
If this is the case let me know I'll update publish and try again.
