### ISSUE TITLE
Registration: re-put Terms and Conditions.

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#319]
In the old registration we had the terms and conditions that had to be approved before the registration.
Now it looks to me that this is lost... but is needed.

**Comment by mmenapace** [comment]
Waiting for legal support

**Comment by pcampanella** [comment]
Betty please update this: you can ask help to Marco. 
There is a link in the keycloak login page: it is the old link, you need to update with the new EULA released in docs.
![image](https://user-images.githubusercontent.com/6428249/187503205-120a917f-ca90-451d-baad-7b9b16700f15.png)
Then also in the registration page, I would like to add an explicit check that they have seen and accepted conditions.
@mmenapace : we had it or not? Can we add ?
