### ISSUE TITLE
Search Section: change the tabs of different missions

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#327]
The different missions now have a checkbox.
We need to change using or a radio button or a combo box.
The search feature now MUST have one and only one mission.

**Comment by mmenapace** [comment]
To improve user experience, on result bar, instead of reporting "-1" in case of error show a dedicated icon.
(partially mitigated by single provided search)
Also, make the selection of the bounding box mandatory? Show a reminder before launche the search on the entire globe?

**Comment by mmenapace** [comment]
Changing the number of product per page does not update the number of available pages
