### ISSUE TITLE
Check workspace access control policy 

### ISSUE THREAD

**Issue by mmenapace** [fadeoutsoftware/WASDI#329]
Users can access workspace, even if the sharing with them was removed, by using the id of the workspace.
E.g. If a WS link is kept in the bookmarks the user can access to it.

**Comment by ppetrescu-wasdi** [comment]
The observation was true, any user could access a workspace.
However, **any** user could access **any** workspace regardless of previous shared access-rights.

fixed on the "feature/providersLauncherConfig_fix_workspace_access" branch.

**Comment by mmenapace** [comment]
Added test of the received viemodel.
The client force the user to the home if it's empty. 
Tested & merged in develop.
