### ISSUE TITLE
Queues splitting

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#33]
We have two queues (processing, download), I propose we adopt 4 queues who use distinct resources:

1. processing (uses CPU)
1. download (uses download band)
1. upload (uses upload band)
1. copy (uses FS I/O)

**Comment by pcampanella** [comment]
I agree but we have to study it a little bit better. At the moment we cannot distinguish between copy and download. 
Is something that we discover while is running. Let's talk about it.
