### ISSUE TITLE
sometimes bands cannot be opened (getBandImage) in a non predictable way

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#34]
Sometimes some bands cannot be opened.

As an example refer to S2A_MSIL1C_20181212T001711_N0207_R116_T55MHP_20181212T013828.zip

the issue seems to disappear after tomcat is restarted

**Comment by pcampanella** [comment]
@kr1zz I think that the better solution is to move get band image in a separate process. Still to solve how to stream the image from a process outside the tomcat one.
