### ISSUE TITLE
Delete workspace with running applications: launcher process can hang on the server (killProcessTree)

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#349]
If a user deletes a workspace while one or more app are running, the web server deletes all the related entries including the process workspace. So now the scheduler does not see the process workspace anymore and the launcher process may hang.

I think, to solve, before deleting the workspace we should:

Find any root processs workspace in running in that workspace.
Kill that tree.

**Comment by kr1zz** [comment]
See this one too:
[Workspace deletion does not stop running processes](https://github.com/fadeoutsoftware/WASDI/issues/230) #230

**Comment by mmenapace** [comment]
Proposal : 
Before delete anything, launch KILLPROCESSTREE to the parent processobjID.
After the completion of the kill process tree follow the normal code flow(delete resources on DB,Geoserver & co.).
