### ISSUE TITLE
Libs -> Wait for processes: control if the list is empty

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#351]
The method does not check if the list is empty. This can bring to an infinite loop.

**Comment by kr1zz** [comment]
-> if the list is empty then return

**Comment by ppetrescu-wasdi** [comment]
fixed with help from Paolo and Cristiano.
There was already a check for the empty list.
The "waitForResume" method (and all its references) was revisited.
the commit was done on the "feature/providersLauncherConfig" branch.
