### ISSUE TITLE
killProcessTree: risk with pids

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#357]
The shell execute kills the given pid, but three situations may happen:

1. the process is still running and it was launched by the desired launcher -> good
2. the process is no longer running -> not good, but no problems either
3. the process assigned to that pid exists but the system actually reassigned the same pid to another process -> **bad**

The latter won't happen very often, but with a growing number of processes we cannot ignore it. Checking for the appropriateness of that pid is not easy either. If we check that the process is still RUNNING we may have a race condition (it may change state in the meanwhile and the pid might be in cases 2. or, worse, 3.). Moreover, some processes might be in a terminal state (ERROR, DONE, STOPPED) but the processes they launched might still be running, so it's not be a bad idea to try and kill them anyway.

**Comment by pcampanella** [comment]
I think there is no unique solution. And the new version is going to kill the dockers directly. So I close this issue.
