### ISSUE TITLE
Race condition in process / workspace deletion (WorkspaceResource - ProcessWorkspaceResource - killProcessTree)

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#358]
1. deletion of workspace A starts
2. another process, from workspace B, opens workspace A and launches a process there, before the delete operation completes

What happens? We should prevent the launch of processes in workspace A. Need to adopt some sort of synchronization

**Comment by pcampanella** [comment]
No more allowed switch workspace while running
