### ISSUE TITLE
Client: Double Notification on file Donwloaded

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#37]
It looks that when a file is donwloaded, ingested in WASDI, the client gives two notifications of the same message. I mean the "display" notification on the lower right bottom of the screen

**Comment by dfiori** [comment]
The issues seems related with `receivedRabbitMessage ` into `ImportController`. It perform a switch/case and show a dialog (with the same text  for all message-type), then another dialog is shown by `utilsProjectShowRabbitMessageUserFeedBack `again with a switch case (here the text change according with message-type).
The first switch/case has been commented, but a test around the app is required to verify correctness in other app sections.
