### ISSUE TITLE
Markeplace - Automatic UI : add a floating number input

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#376]
The system at the moment allows to insert an integer.
We should add the possibility to insert a floating number.

**Comment by mmenapace** [comment]
Float and integers and handled directly from the JS side. 
Input is limited to numbers and dot.

**Comment by pcampanella** [comment]
Did not work for me. At least, this does not set the default.
To reproduce, in test.wasdi.net where is published.
Go in the Hasard 3 Inputs app (I shared with Marco)
Change 
               {
                    "param": "ASHMAN_COEFF",
                    "type": "text",
                    "label": "Ashman Coefficient",
                    "default": "2.4"
                },
                in type "numeric".
                
                The control is show but the default no.
                
                
                PLEASE REMEMBER TO RE-SET TEXT AFTER THE TEST. The app is production.

**Comment by mmenapace** [comment]
Ashman Coefficient field was of type "text" and not showed: it should be "numeric" 
The template is generated accordingly to specification, when clicking on button.
Resetting to "text" -> will not render anything because the valid alternative is "textbox".

The default is not set. Fixing it

**Comment by mmenapace** [comment]
Fixed and tested on test.wasdi.net.
A convertion of the value to float was required to pass the number to the control.
Reverted to "textbox" on App UI in order to have application working also on main node.

**Comment by mmenapace** [comment]
reopened because JSON is not updated on value change
