### ISSUE TITLE
Implement IsValid method on Parameters hierarchy

### ISSUE THREAD

**Issue by mmenapace** [fadeoutsoftware/WASDI#387]
Parameters passed to Launcher are in fact POJOs composing a single level hierarchy that starts from BaseParameters.
In order to check such parameters before passing them to the launcher, an improvement can be to implement a validation for each.
The validation of the base parameters its extended with the expected ones from the sibilings.

E.g. 
class BaseParameters {
[...]
protected booleanisValid(){[...]}
}

class Sen2CorParameter{
[...]

protected boolean isValid(){
      return super().isValid && [...]
}
}

**Comment by kr1zz** [comment]
Why protected? Who is supposed to launch the validation?
