### ISSUE TITLE
Add Update Review and Comment Function

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#389]
If the user is the owner of a Review or a comment, he should be able to update it.
It is now possible to insert and delete but not to update.

The API is ready on the server and also on the client:

ProcessorMediaService.updateProcessorReview
and updateReviewComment

But these functions are never called in the client.

**Comment by ppetrescu-wasdi** [comment]
added update functionality for comments;
added update functionality for reviews;
added missing refresh of reviews upon deletion;
added missing removal of orphan comments when the parent review is cancelled;
added multiple deletion feature to MongoRepository;
