### ISSUE TITLE
Workflows Dialog: waiting displaced

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#390]
The waiting alien is displaced in the workflows dialog:
![image](https://user-images.githubusercontent.com/6428249/138317600-0c3dfa18-8e7c-4f43-9a1c-0cba7279f1f2.png)

Can be reproduced very well in debug because it is quite slow to show the worflows.
The alien should be seen all and at the top or in the middle of the window.

**Comment by mmenapace** [comment]
Fixed on branch UI Fixes.
Still not merged because some feature requires further discussion

**Comment by pcampanella** [comment]
ok now is better but at least to me the dialog has a problem in the bottom part: look how many blank space 

![image](https://user-images.githubusercontent.com/6428249/143293659-afa46705-5549-46c0-8f6b-fd639c0d2aaa.png)

**Comment by mmenapace** [comment]
Feedback from Petru and Cristiano: 
no blank space for 1080p and 100%-125% resolution
