### ISSUE TITLE
logout - redirect on home page

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#40]
It looks that now, when the user selects logout., the system does not redirect on the home page and the user can see all the WASDI sections. He is unlogged and API are safe, but this is a bad behaviour, user must be redirected to home page.

**Comment by dfiori** [comment]
quando utente fa logout viene pulito il workspace?
this.m_oConstantsService.setActiveWorkspace();

Controllare se viene controllata la sessione
AuthService.checkSession
(deve essere quella parte a fare il redirect se è scaduta sessione)
