### ISSUE TITLE
Client - Change Workspace Node does not update workspace URL

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#421]
when you create a new workspace you can go in the info button of the editor and change the node.
It updates the db but does not update the workspace addess on the client so for example if you try an ingest (upload) the file is uploaded in the "old" node and not in the new one.
Also, process workspaces are not visible.
We must update the address in the workspace object once an update is done.

**Comment by pcampanella** [comment]
This does not work.
In the WorkspaceDetailsController there is:
                // update on the current active workspaces
                oController.m_oConstantService.getActiveWorkspace().nodeCode = this.m_sCurrentNode;
               // oController.m_oConstantService.getActiveWorkspace().apiUrl = oWorkspaceViewModel.apiUrl;

But first of all we need to call oController.m_oConstantService.setActiveWorkspace with the full returned view model. Still better should do this in a callback in the editor controller, when the dialog is closed with success so that we can update both constantservice and EditorController.m_oActiveWorkspace.

**Comment by pcampanella** [comment]
It does not work yet. I tried to add the set to constant service "al volo" but not work yet.

to reproduce:
in test create a workspace
change from default (creo2) to ONDA1
go in search and add an image
go back in editor (WITHOUT passing by the workspaces section)
Check with the network that the API are still for creo2

**Comment by mmenapace** [comment]
check commit dafcd332 on  /hotfix/updateWorkspaceUrl
