### ISSUE TITLE
Error: [ngRepeat:dupes] when opening the App Parameters Templates page 

### ISSUE THREAD

**Issue by ppetrescu-wasdi** [fadeoutsoftware/WASDI#428]
Access the application and open a workspace (any). Click on the "Apps" button to see the "Applications" page.
Each application card has a new button (cogs) that, when clicked, opens a new modal window: the "App Parameters Templates" page.

At this point, on the DevTools console, an error has been thrown:

```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.8.2/ngRepeat/dupes?p0=(key%2C%20val)%20in%20child&p1=string%3As&p2=s
    at angular.js:99
    at angular.js:34028
    at angular.js:19132
    at m.$digest (angular.js:19270)
    at b.$apply (angular.js:19630)
    at HTMLButtonElement.<anonymous> (angular.js:29127)
    at HTMLButtonElement.dispatch (jquery-3.5.1.min.js:2)
    at HTMLButtonElement.v.handle (jquery-3.5.1.min.js:2) 
```

From the initial investigation, it appears that the problem is not with the code of the new modal page, because the error is shown even when substituting the current code with a simple paragraph ```<p>some message</p>```

**Comment by pcampanella** [comment]
Check if the problem is there. Spend some time to try to solve but, caution, when this issue was insterted we already lost a lot of time without success. So if after, half a day we have no idea but it works, please let me know to decide if we should go on or no.
