### ISSUE TITLE
Apps -> Template -> Apply -> Run: after this a gray screen stays on top and you need to refresh

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#437]
As described in the title this sequence creates problems:

Open a Workspace
Open Apps
Select an app where you have a template
Apply the template
Run the App

the system will show logs window.
When done, you click close but a black transparent screen blocks you

This is related for sure to the "open dialog". or better how is closed.
Reproduce in test.

![image](https://user-images.githubusercontent.com/6428249/144655459-cb949586-562f-4c0c-9ca1-51aaafb19aae.png)

**Comment by mmenapace** [comment]
working on hotfix/ClosaAppLaunchDialog 
Modified the timeout to 200 mS and, from my environment, the problem is fixed.

**Comment by mmenapace** [comment]
Tested with parameter composed by 2000 lines
