### ISSUE TITLE
Docker templates -> get-pip.py

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#453]
Check the pyton37 docker template. There is a legacy get-pip.py file. If I'm not wrong this is not used anymore. 
If confirmed we should delete if from all the servers.

**Comment by wasdi-sysadmin-br** [comment]
**Update:**

I removed get-pip.py from docker template + processor on all servers except test > onda has the server is no longer used.
I backuped file in /root/2021-12-20_backup before to remove it: we can remove in 7 days (I have a reminder)
This ticket is finished.
