### ISSUE TITLE
Import ShapeFile

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#459]
Need to improve shape file support: if the user uploads a zip we should check if it is a shape file and, in case ingest it.

**Comment by kr1zz** [comment]
I looked at this: don't we already handle zipped shapefiles? Do you have some counterexamples, i.e., some file that is not supported, at hand?

`Ingest.java` (at the moment this is at line 94):

```java
if (oShapeFileUtils.isShapeFileZipped(oFileToIngestPath.getPath(), 30)) {
```

**Comment by pcampanella** [comment]
Did you test it? 

I’m pretty sure when I tried to upload a shape did not work….
