### ISSUE TITLE
Add Automatic Provider Selection to Search

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#47]
The user should be able somehow to select automatic data provider also from the user interface.

**Comment by kr1zz** [comment]
Speaking of redesign, I also suggest to move the map controls to the left side, to make the UI more ergonomic (i.e, don't force the user to move the pointer to the opposite sides of the screen to complete the operations). I already discussed this opportunity with @sergin13  and @dfiori 
![controlsmoveproposal](https://user-images.githubusercontent.com/2588293/53798032-b9889d00-3f37-11e9-8d06-b17ac37c4a55.png)

**Comment by kr1zz** [comment]
# Related

- [footprints stay on map](https://github.com/fadeoutsoftware/WASDI/issues/106) #106

**Comment by kr1zz** [comment]
Maybe we might open more (related) issues, but, as discussed earlier with @pcampanella , and just as a memo:

- support Copernicus-land via ONDA
- support Copernicus-marine via ONDA
- improve free text search
