### ISSUE TITLE
Sentinel-3 download not importing images in workspace (S3)

### ISSUE THREAD

**Issue by LauraGiustariniRSSHydro** [fadeoutsoftware/WASDI#475]
When trying to add a S3 image from Search, it does not do it any anymore:
![image](https://user-images.githubusercontent.com/87178514/149918414-e7d03c5a-9385-4d31-9827-eaa192f74139.png)
neither from Sentinel nor from CREODIAS.

Also, when using from script:
wasdi.importProductList(aoFound)
if aoFound is a list of S3 products (correctly found and listed), it throws an error and does not import anything into the workspace.

I also tried 
wasdi.importProduct(sP0)
with sP0 the first product of the list and still it does not work.

**Comment by kr1zz** [comment]
We download the images. We cannot open all of them with SNAP: https://forum.step.esa.int/t/processing-s3a-sr-1-sra-data/12437/2

**Comment by kr1zz** [comment]
Actually, the download always works, it's just that [we cannot (easily) read every Sentinel-3 product](https://github.com/fadeoutsoftware/WASDI/issues/462).
