### ISSUE TITLE
Production -> Logout -> wrong address

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#488]
The logout brings the user to keycloak page and not to wasdi home.

**Comment by mmenapace** [comment]
I've made a little investigation after re-discoverying the problem: 
To the best of my knowledge, the redirect URL is composed of 
[BASE URL][URI]
on the code side on Logout function in RootController we impose a wrong [URI] which is "../#/home" -> this doesn't represent any resource on server (the correct one would be "/#!/home") but, as /#!/home is the default falback it works on test.

I've tried to edit the wasdi client to use [BASE_URL] = "www.wasdi.net", but without success.
The new value is ignored.
Does it require a restart of the service?

**Comment by mmenapace** [comment]
Fixed and tested in production. 
Added a new parameter to config.json with the baseurl. 
This parameter is used to initialize the redirect uri

**Comment by mmenapace** [comment]
check hotfix/keycloakLogout branch
