### ISSUE TITLE
Ubuntu servers - creodias - migrate from ifupdown to netplan

### ISSUE THREAD

**Issue by wasdi-sysadmin-br** [fadeoutsoftware/WASDI#502]
Creodias servers use ifupdown for network configuration
Other servers (except the CentOS server) use netplan

2 problems:
1/ little problem: servers are not aligned
2/ we can't finish the ticket https://github.com/fadeoutsoftware/WASDI/issues/464: with ifupdown, we can't say "ignore DNS servers sent by the DHCP"

If possible I would like to migrate to netplan
This ticket is risky: we can lose control of the server that's why we need to test console access first

**Comment by pcampanella** [comment]
Also on this I do not know if there are news

**Comment by wasdi-sysadmin-br** [comment]
It's not done yet.
To do this, we should:
- rent a little VM
- test/repeat operations
- organize the migration:
  - as it's risky, we can't do this operation during another maintenance: it must be a dedicated maintenance
To note:
- I don't know if it will work definitively or not
- when a new server is installed or an existing server is reinstalled, the "problem" will be reintroduced: it is related to the image used to install the servers

**Comment by wasdi-sysadmin-br** [comment]
After a discussion, we close this ticket.
