### ISSUE TITLE
Registration form: no message when the user already exists

### ISSUE THREAD

**Issue by wasdi-sysadmin-br** [fadeoutsoftware/WASDI#535]
If we try to register using an e-mail address already associated to an existing account in Keycloak, we stay on the registration form without message.
It can be confusing for a user because it gives the impression that nothing is happening when in fact it is because the account already exists.

Maybe we can add a message to say "This account already exists. Do you want to reset your password?" or something like that.
Just a detail: it means we give the information to the person that the account already exists and it can be considered as a vulnerability

**Comment by pcampanella** [comment]
Betty Please check. If you do not have enough info in the client, ask in discord to server side team what you need. If you already can recognize the situation just add the message for the user.
