### ISSUE TITLE
Search S5p Timeliness: filter (Offiline, Near Real Time, Reprocessing) does not seems to work

### ISSUE THREAD

**Issue by LauraGiustariniRSSHydro** [fadeoutsoftware/WASDI#539]
When doin the following Search (over Iraq, bbox drawn by hand):
2022/04/01 - 2022/04/01
S5P
LEVEL2
L2__NO2___
Offline
![image](https://user-images.githubusercontent.com/87178514/162721177-d49e8543-c87e-4b8d-862c-fc5e8396d683.png)

It returns 4 products, 2 NRTI and 2 OFFL
![image](https://user-images.githubusercontent.com/87178514/162721338-bc51cfe3-6ba9-43ec-9bd8-cfe874309d9f.png)

**Comment by LauraGiustariniRSSHydro** [comment]
Also, the same Search with Timeliness = Near Real Time
returns 0 products, when indeed there should be products
![image](https://user-images.githubusercontent.com/87178514/162726834-cd60528c-23db-48ee-8a4e-e1f6fecccdfc.png)

**Comment by pcampanella** [comment]
@LauraGiustariniRSSHydro  can you please check if it is fixed?
Thanks
