### ISSUE TITLE
Client - JSon editors -> add a button to format

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#542]
We should add a button to format json for example in the UI Editor but maybe also in the other dialogs that handles json like the params one..

**Comment by pcampanella** [comment]
As minimum, as written in the Issue, we should add a button that forces the formatting. 
Indeed the formatting is done automatically when the form is shown, we just need to re-do with a dedicated button.
The same button can be added in the App->Edit App -> Edit UI 
but also in the form "advanced apps", where the user can input the json to pass to the app.

**Comment by bspurgeon08** [comment]
I've pushed an example to the search params page (where the user writes JSON), but I'm not sure to what degree we want the JSON formatter to work.

I tried making it able to correct minor mistakes, but maybe this is too much? Should it just format correct JSON that isn't pretty?
