### ISSUE TITLE
Java, C# and if possible other libs: add a dictionary in input to searchEOImages

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#546]
It has been added in python:
    if aoParams is not None:
        try:
            for sKey in aoParams:
                sQuery += " AND " + sKey + ":" + aoParams[sKey]
        except:
            wasdiLog('[WARNING] waspy.searchEOImages: exception adding generic params')
The dictionary can be used as a key/value pair to add filter specifics of each kind of data.
The code must only add the key:value to the query.

**Comment by ppetrescu-wasdi** [comment]
done for Java
