### ISSUE TITLE
App deletion: bug in the window modal

### ISSUE THREAD

**Issue by wasdi-sysadmin-br** [fadeoutsoftware/WASDI#566]
Steps to reproduce:

1. Connect
2. Open a workspace
3. Click on "Apps"
4. Delete one of your own application

The application is still present in the window modal but in reality is deleted
If you close the modal window + to reopen it, your application is absent

**Comment by pcampanella** [comment]
Please Betty verify in test and if confirmed solve it.
YOu can deploy your own app in test for debugging.

**Comment by pcampanella** [comment]
See my comment on Discord. Now we added a timeout. We need to manage the asynch notification instead.
