### ISSUE TITLE
DEM Data Provider: fileName property without .tif

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#572]
When we search DEM images from libs, the returned ViewModel has the property fileName but it is without the .tif extension.

Add the extension to the property to be consistent with other Data Providers.
Indeed, check also World DEM.

**Comment by ppetrescu-wasdi** [comment]
added the missing format to the properties map.

committed in **develop** and **feature*jenkins**.
deployed in **TEST**.
