### ISSUE TITLE
Enhance app launcher giving "current Workspace" option

### ISSUE THREAD

**Issue by mmenapace** [fadeoutsoftware/WASDI#575]
When an user open an application from the market has 2 option:
- Create a new workspace (with date and application name)
- Open an existing workspace
It could be an enanchement to gives a third (default?) possibility: if the user has an opened workspace
use it.

(attached ref. Image) 
![image](https://user-images.githubusercontent.com/26542988/172800720-b9e3d0bf-0f19-4f88-9798-0ca2f634af79.png)

**Comment by pcampanella** [comment]
@bspurgeon08  since you use the other dashboard, I tagged you here to let you remember this :)

**Comment by bspurgeon08** [comment]
@pcampanella - I have implemented this in the new client and now I will start in this one
