### ISSUE TITLE
wasdi.deleteProduct seems to remove only from workspace

### ISSUE THREAD

**Issue by LauraGiustariniRSSHydro** [fadeoutsoftware/WASDI#581]
The function 
wasdi.deleteProduct(sProduct)
with sProduct= name of the product in the workspace (without directory)

seems to remove the product sProduct from the workspace but NOT from the disk.

**Comment by pcampanella** [comment]
I added a comment in the method.
I agree that is true but I find dangerous to delete files so I'll let the user do it locally, declaring this!
