### ISSUE TITLE
Package Manager UI Not Updating in Conda

### ISSUE THREAD

**Issue by bspurgeon08** [fadeoutsoftware/WASDI#641]
**User feedback:** 
1. open the app and open my application conda_test_app
2. go to package manager and write networkx and then click on Add package and then on the confirmation dialog I confirm that I want to install this package
3. Then the UI changes in some kind of loading screen while the package is being installed
4. Loading screen stops and now I am expecting that the package is installed, but if I scroll down and check if there is the package I was just installingm, it is missing. (Here is where I would expect to see the package I just installed) - if I close the window with all the packages and open it again I can find it... (what I am trying to say here is that it works properly, but the UI does not update as I would expect)

**Comment by pcampanella** [comment]
It looks the same also in PIP.
We may have introduced some new bug after we solved last time. We need to check.
