### ISSUE TITLE
Package Manager - Name and version of the engine not shown

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#643]
In the package manager dialog if I remember well it was supposed to have the [name of the app] Packages - [Name and version of the package engine]

Or something similar but now we have nothing after the - 
![image](https://user-images.githubusercontent.com/6428249/199942569-401a26d6-17b4-490f-aa58-e02df3adca57.png)

We should check what was supposed to be there and fix.

**Comment by ppetrescu-wasdi** [comment]
Fixed by changing the source of truth.
Instead of making a live call to the Flask server running on the Docker container, I switched to the packagesInfo.json file.
