### ISSUE TITLE
Package Manager -> Add a button to force the update of the list

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#647]
In the PM dialog we should add a button to force wasdi to refresh the list of the packages.

**Comment by ppetrescu-wasdi** [comment]
(dirty) fixed it by hijacking the "Add package" functionality.
therefore, when the user clicks on the "Refresh List" button, an "Environment Update" action is triggered on the Java side (with the update command being null). The Java code simply refreshes the packagesInfo.json file.
