### ISSUE TITLE
Base Layer change: does not work

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#65]
The base layer change does not work.
I think we cannot use google for licence purpose: check licence?
Check this site:
https://leaflet-extras.github.io/leaflet-providers/preview/

I suggest:
The actual base one
Thunderforest.SpinalMap
OpenTopoMap
Esri World Street Map
Esri World Imagery
NASAGIBS.ViirsEarthAtNight2012

**Comment by sergin13** [comment]
Thunderforest.SpinalMap dosen't work...

**Comment by pcampanella** [comment]
It is not so important at all, but strange, in the sample online for me now is working.

**Comment by pcampanella** [comment]
Please REMOVE GOOGLE and ADD THESE:

Thunderforest.SpinalMap
OpenTopoMap
Esri World Street Map
Esri World Imagery
NASAGIBS.ViirsEarthAtNight2012

**Comment by pcampanella** [comment]
Now is ok BUT STILL MISSING:

Thunderforest.SpinalMap

**Comment by pcampanella** [comment]
Thunderforest needs an API Key. So we will not add it.
