### ISSUE TITLE
ONDA Query: get missing info as available in the DhUS search

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#68]
When the user make a search WASDI has to know:

Date | 
Instrument |  
Satellite |  
Mode |  
Relative orbit |  
Size | 393.63 MB
Polarisation

ONDA is not getting this info. From the onda catalogue these are avaiable.
From the Onda guide it looks like the Product Entity should have the Metadata nested entity. We need to check if info are there or check which is the calls that the ONDA web catalogue does to have all the informations.

**Comment by kr1zz** [comment]
second call needed

**Comment by kr1zz** [comment]
Metadata mapping seems wrong: check this example (using querylist)
![ondametadataerror](https://user-images.githubusercontent.com/2588293/52639628-f8957680-2ed4-11e9-9a72-8225fbfd67a3.png)
