### ISSUE TITLE
GPOD WPS Authentication

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#7]
The GPOD WPS service requires EO-SSO Auth to be executed. EO-SSO does not have a machine to machine interface. A kind of proxy must be implemented.

Here there is a shell script that simulates the login and takes the cookie to add to the request

https://github.com/spinto/secp/blob/master/secp

Row more or less 888.

We should investigate and implement a solution like this.

**Comment by kr1zz** [comment]
Is this an alternative?
https://edugain.org/

**Comment by pcampanella** [comment]
> Is this an alternative?
> https://edugain.org/

No. These are two different things. Thank for the link!

**Comment by kr1zz** [comment]
# Status

[WIP]: fiddling around [WPS client](https://52north.org/software/software-projects/wps/) (see below)
2018.01.22: Managed to authenticate on EO SSO from java code

# doing

check for presence of http connections in the following:

- [ ] org.n52.wps
  - [ ] org.n52.wps.client
    - [ ] ExecuteRequestBuilder
    - [ ] WPSClientSession
    - [ ] ExecuteResponseAnalyser
  - [ ] org.n52.wps.io.data
    - [ ] IData
- [ ] net.opengis.wps.x100::
  - [ ] ProcessDescriptionType
  - [ ] CapabilitiesDocument
  - [ ] InputDescriptionType
  - [ ] ExecuteDocument
  - [ ] ExecuteResponseDocument
- [ ] org.apache.xpath.objects
  - [ ] XObject
