### ISSUE TITLE
Delete Workflow: add confirm window pop up. And let the delete only for owner of public wf

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#70]
When a user delete a Workflow add the display pop up to ask confirm.
Hide the delete button for public workflows when visible to users that are not the owner.

**Comment by sergin13** [comment]
I don't think is possible see the workflows of the other users ....

**Comment by pcampanella** [comment]
Yes I added the possibility to have Public Workflows. Refer also to #74

**Comment by pcampanella** [comment]
ALMOST DONE: but still, if it is not "mine" I should not have the possibility to delete.

![image](https://user-images.githubusercontent.com/6428249/52504514-fbe4e580-2be8-11e9-94b0-085dadf08641.png)

REMOVE the trash for non-owned workspaces
