### ISSUE TITLE
No subscription when we connect using "WASDI Login 2.0"

### ISSUE THREAD

**Issue by wasdi-sysadmin-br** [fadeoutsoftware/WASDI#705]
When I connect with my user with the WASDI client + if I have a subscription: it works
When I connect with the SAME user through Keycloak "WASDI Login 2.0": I have the button "purchase subscription"

**Comment by pcampanella** [comment]
I just tested this one, and it looks still True to me.
This is a very bad bug. We need to solve it soon.

**Comment by leonevalentina** [comment]
Hi @pcampanella,

I had a look at this issue with @bspurgeon08 this morning. 

We actually noticed that there is an endpoint already being called by the client after the authentication with Keycloak: `/wasdiwebserver/rest/auth/checksession` which returns a user view model. 

The endpoint gets the user information from the session relying first on Keycloak and eventually on the DB.
With the user view model being returned, the client could get the same information that is returned from the "legacy login" and that is missing from the keycloack login (i.e. subscription type and role). 
We would just need to do some adaptation on the client side to use that information and on the back-end side to fill all the information (some of the field of the view model are not filled). Could it be this an option?

For what you mentioned to me about checking how/where to configure the keyloack redirection to WASDI after the login, I think Marco today is unavailable, so I will talk to him when he is back
