### ISSUE TITLE
Login: force user Id to lower case

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#728]
we had a issue with a user that used the mail not all in lowercase.
We should force lowercase in the different access of the user (login) checking both cases.
PS
Then we can fix manually the problem of the user that rised the issue.

**Comment by leonevalentina** [comment]
Just a reminder on this: the user who raised the issue is not the only one who registered using some upper case letters, there are a couple more users in the db. We should fix all of them

**Comment by leonevalentina** [comment]
Fix pushed on prod to make the login and registration case-insensitive. 
No matter which combination of lower and upper case letters a user will type, we will force the user id to have all lower case letters in our db. 

We also fixed manually in the db the user ids of the person rising the problem and other two persons which registered using a combination of lower and upper case characters. More information about the process in Confluence page: "BE > Support request > Migrate accounts"
