### ISSUE TITLE
Editor -> Product Context Menu disabled entries

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#75]
Filter Band, Mask Manager, Zoom voices are never enabled. They should be enabled when clicked on a band.

**Comment by sergin13** [comment]
Usually this commands are enable only if the band is checked 
![2_li](https://user-images.githubusercontent.com/22172012/52128022-29072600-2634-11e9-9881-2151eb472612.jpg)

**Comment by pcampanella** [comment]
Change it: Enable Disable should be related to the presence or not of the 2D Map or 3D map, both in the main window or in the navigator window.

Filter Band And Mask manager ok, for now let as they are, they are going to be changed in Edit.
