### ISSUE TITLE
Cannot add file to WASDI from Jupyter Notebook

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#750]
Open a Jupyter
create or save somehow a file in wasdi.getSavePath()
try addFileToWASDI -> with some file it works, with most it doesn't

**Comment by pcampanella** [comment]
The file was a geotiff that gdal can read but snap no. It was a Uint16 but saved with 15 bits.

**Comment by kr1zz** [comment]
It looks like SNAP may not be able to open GeoTIFFs, depending on the data type. UInt16 is one of these types.

SNAP also has the opportunity of opening files using GDAL, we need to understand how to trigger it.
