### ISSUE TITLE
Plan-> Check all nodes

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#76]
It looks that check all is not working. Check and if it is the case fix

**Comment by sergin13** [comment]
The check all doesn't exist in plan, the button named "checked nodes" open all the checkED nodes ( i just renamed it in open checked nodes)

**Comment by pcampanella** [comment]
Ok.
Change the labels:

Open Checked
REMOVE  (comment)close nodes
REMOVE  (comment)open nodes 
Clear (actual deselect nodes)
