### ISSUE TITLE
Implement WPS Launcher Operation

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#89]
Take from the web the parameter with (indicative!!!!!!!!!!!)

xml payload
wps processor id (our internal code)
wps operation
wps provider (to use for auth)

Add a case in the launcher
make the wps request
use get status the get the update
remember to close the process in any case

**Comment by kr1zz** [comment]
http://cite.opengeospatial.org/pub/cite/files/edu/wps/text/operations.html

**Comment by kr1zz** [comment]
There was [a bug](https://github.com/52North/wps-client-lib/issues/8) in the library we use for parsing the result. It was blocking since the response parsing failed. It is fixed now.
