### ISSUE TITLE
Tiling Service in IDL

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#92]
Add the Tiling service in WASDI. The tile should be able to recut a big image in requested smaller areas.
The service has to be included in the WASDI lib and callable from IDL

**Comment by pcampanella** [comment]
Here some useful reference:
https://forum.step.esa.int/t/snap-clip-raster-by-shapefile/4803

**Comment by kr1zz** [comment]
As an alternative (if appropriate), we may consider doing the clipping with geoserver:
- if the input is a tiff, do a HTTP GET `GetCapabilities` request and look for `crop` or `clip`, there are many options
- alternatively, it might be possible to [work directly on the image mosaic](https://docs.geoserver.org/stable/en/user/tutorials/imagemosaic_footprint/imagemosaic_footprint.html)
