### ISSUE TITLE
Wasdi Lib (start from Java): add auto unzip in the download method

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#97]
The download method (triggered by getFullProductPath) can now use auto-zip feature. In the download file is a .zip we need to check if it is a self-zipped file or native zip.
If it is a self-zipped we need to unzip.
At the moment we are using .zip only for ".dim" files.
Probably is better to add a wasdi.zipped file or similar in the auto-zip so that we have an unique way for this problem also in the future (think ie at shape files...).

**Comment by kr1zz** [comment]
Related issues:

- #96 
- #85

**Comment by kr1zz** [comment]
Instead of adding a dummy file I'm trying to [add a comment](https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipOutputStream.html#setComment(java.lang.String)) and [read it](https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipFile.html#getComment--)
